### ISSUE TITLE
Can we filter by number of arguments to a call?

### ISSUE THREAD

**Issue by stevenjackson** [testdouble/referral#7]
I'm doing an `I18n.t` investigation and a change to the method signature means I need to investigate all cases that take 2 or more arguments.  Unfortunately hundreds of calls only take one.  Many of the calls are using string interpolation or are styled as multi-line, so pattern matching isn't a great fit.

I'll try and dig into this next week, but thoughts on checking arity are appreciated.

**Comment by searls** [comment]
The first place I'd look is https://github.com/testdouble/referral/blob/master/lib/referral/filters_tokens.rb

If adding a new filter function (proc) has enough info about the node already, that's a great start. I suspect it does not, however, and that this `Value::NodeType` would need to be expanded to incorporate args as an attribute ([see this](https://github.com/testdouble/referral/blob/master/lib/referral/token_types.rb#L104-L112)).

Finally, if that all does appear necessary, the actual scanning of nodes would need to be updated to incorporate it ([see this](https://github.com/testdouble/referral/blob/master/lib/referral/scans_tokens.rb))
